### ISSUE TITLE
Cloud.Reviews.query does not return "user"

### ISSUE THREAD

**Issue by kim1059** [aaronksaunders/AppC-Alloy-Book#2]
Hello and thank you for the tutorials. 

I was going through the application you created and stumbled upon a problem with the reviews.query api. According to the API it doesnt return information about user other than his id. but in your example you try to retrieve information about the user. API outdated maybe?

**Comment by aaronksaunders** [comment]
That code in the book was written over a year ago so it is quite possible
that the API has changed... You can always just make an additional API call
to get the user information or create a relationship with a custom field,
or store the information you need as a custom field in the review object when
you save the review

On Friday, February 20, 2015, kim1059 <notifications@github.com> wrote:

> Hello and thank you for the tutorials.
>
> I was going through the application you created and stumbled upon a
> problem with the reviews.query api. According to the API it doesnt return
> information about user other than his id. but in your example you try to
> retrieve information about the user. API outdated maybe?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/aaronksaunders/AppC-Alloy-Book/issues/2>.
>


-- 
-- <http://www.clearlyinnovative.com/build-it/>
--

Aaron K. Saunders
CEO Clearly Innovative Inc.
aaron@clearlyinnovative.com
201.214.5926  (M)
blog@clearlyinnovative.com
www.clearlyinnovative.com
@aaronksaunders





This email message and any attachment(s) are for the sole use of the
intended recipient(s) and may contain proprietary and/or confidential
information which may be privileged or otherwise protected from disclosure.
Any unauthorized review, use, disclosure or distribution is prohibited. If
you are not the intended recipient(s), please contact the sender by reply
email and destroy the original message and any copies of the message as
well as any attachment(s) to the original message.

**Comment by kim1059** [comment]
thanks for quick reply. I will surely do so
